# kubectl apply -f client-pod.yaml
# kubectl describe pod client-pod
# kubectl delete -f client-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: stephengrider/multi-worker:latest
      ports:
        - containerPort: 9999
